export type GameMeta = {
  code: string;
  href: string;
  en: string;
  bn: string;
  tag: string;
  players: string;
  cover: string;
  gradient: string;
  category: "hot" | "slots" | "crash" | "table" | "provider";
  provider?: string;
};

export const GAMES: GameMeta[] = [
  {
    code: "crash",
    href: "/games/crash",
    en: "Aviator Crash",
    bn: "এভিয়েটর ক্র্যাশ",
    tag: "HOT",
    players: "3.2k",
    cover: "/games/crash.jpg",
    gradient: "from-rose-600 via-red-700 to-black",
    category: "crash",
  },
  {
    code: "dice",
    href: "/games/dice",
    en: "Dice",
    bn: "ডাইস",
    tag: "FAIR",
    players: "1.1k",
    cover: "/games/dice.jpg",
    gradient: "from-indigo-600 to-violet-900",
    category: "table",
  },
  {
    code: "mines",
    href: "/games/mines",
    en: "Mines",
    bn: "মাইনস",
    tag: "SKILL",
    players: "980",
    cover: "/games/mines.jpg",
    gradient: "from-amber-600 to-orange-900",
    category: "table",
  },
  {
    code: "wheel",
    href: "/games/wheel",
    en: "Fortune Wheel",
    bn: "ফরচুন হুইল",
    tag: "SPIN",
    players: "760",
    cover: "/games/wheel.jpg",
    gradient: "from-cyan-600 to-blue-900",
    category: "hot",
  },
  {
    code: "slots",
    href: "/games/slots",
    en: "Neon Slots",
    bn: "নিয়ন স্লট",
    tag: "LUCK",
    players: "1.8k",
    cover: "/games/slots.jpg",
    gradient: "from-fuchsia-600 to-purple-950",
    category: "slots",
  },
  {
    code: "plinko",
    href: "/games/plinko",
    en: "Plinko",
    bn: "প্লিঙ্কো",
    tag: "NEW",
    players: "640",
    cover: "/games/plinko.jpg",
    gradient: "from-emerald-600 to-teal-950",
    category: "hot",
  },
  {
    code: "hilo",
    href: "/games/hilo",
    en: "Hi-Lo",
    bn: "হাই-লো",
    tag: "FAST",
    players: "520",
    cover: "/games/hilo.jpg",
    gradient: "from-sky-600 to-slate-900",
    category: "table",
  },
  {
    code: "jili",
    href: "/games/jili",
    en: "Jili Hot",
    bn: "জিলি হট",
    tag: "JILI",
    players: "2.1k",
    cover: "/providers/jili.svg",
    gradient: "from-red-600 to-rose-950",
    category: "provider",
    provider: "Jili",
  },
  {
    code: "pg",
    href: "/games/pg",
    en: "PG Soft",
    bn: "পিজি সফট",
    tag: "PG",
    players: "1.9k",
    cover: "/providers/pg.svg",
    gradient: "from-amber-500 to-yellow-900",
    category: "provider",
    provider: "PG Soft",
  },
  {
    code: "spribe",
    href: "/games/spribe",
    en: "Spribe",
    bn: "স্প্রাইব",
    tag: "SPRIBE",
    players: "2.6k",
    cover: "/providers/spribe.svg",
    gradient: "from-sky-500 to-blue-950",
    category: "provider",
    provider: "Spribe",
  },
  {
    code: "evolution",
    href: "/games/evolution",
    en: "Evolution",
    bn: "এভোলিউশন",
    tag: "LIVE",
    players: "1.4k",
    cover: "/providers/evolution.svg",
    gradient: "from-violet-600 to-purple-950",
    category: "provider",
    provider: "Evolution",
  },
  {
    code: "fa_chai",
    href: "/games/fa_chai",
    en: "Fa Chai",
    bn: "ফা চাই",
    tag: "FC",
    players: "870",
    cover: "/providers/fa_chai.svg",
    gradient: "from-emerald-500 to-green-950",
    category: "provider",
    provider: "Fa Chai",
  },
  {
    code: "jdb",
    href: "/games/jdb",
    en: "JDB",
    bn: "জেডিবি",
    tag: "JDB",
    players: "910",
    cover: "/providers/jdb.svg",
    gradient: "from-orange-500 to-red-950",
    category: "provider",
    provider: "JDB",
  },
];

export const PAYMENT_METHODS = [
  {
    id: "bkash",
    name: "bKash",
    color: "#E2136E",
    logo: "/payments/bkash.svg",
    noteEn: "Send money then submit TrxID + screenshot",
    noteBn: "সেন্ড মানি করে TrxID + স্ক্রিনশট দিন",
  },
  {
    id: "nagad",
    name: "Nagad",
    color: "#F15A29",
    logo: "/payments/nagad.svg",
    noteEn: "Send money then submit TrxID + screenshot",
    noteBn: "সেন্ড মানি করে TrxID + স্ক্রিনশট দিন",
  },
  {
    id: "rocket",
    name: "Rocket",
    color: "#8B2C8A",
    logo: "/payments/rocket.svg",
    noteEn: "Send money then submit TrxID + screenshot",
    noteBn: "সেন্ড মানি করে TrxID + স্ক্রিনশট দিন",
  },
  {
    id: "upay",
    name: "Upay",
    color: "#F9A825",
    logo: "/payments/upay.svg",
    noteEn: "Send money then submit TrxID + screenshot",
    noteBn: "সেন্ড মানি করে TrxID + স্ক্রিনশট দিন",
  },
];
