"use client";

import { useEffect, useState } from "react";
import { Check, ShieldOff, RotateCcw, X } from "lucide-react";
import { formatCoins } from "@/lib/utils";
import { useToast } from "@/hooks/useToast";

type Card = { id: string; method: string; label: string; accountNo: string; accountName?: string | null; status: string; rejectionReason?: string | null; createdAt: string; user: { username: string; balance: number } };

export default function AdminWalletCardsPage() {
  const toast = useToast();
  const [cards, setCards] = useState<Card[]>([]);
  const [status, setStatus] = useState("ALL");
  const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); const res = await fetch(`/api/admin/wallet/cards${status !== "ALL" ? `?status=${status}` : ""}`, { credentials: "include" }); const json = await res.json(); if (json.ok) setCards(json.data.cards || []); setLoading(false); }
  useEffect(() => { load(); }, [status]); // eslint-disable-line react-hooks/exhaustive-deps
  async function act(id: string, action: "verify" | "reject" | "block" | "activate") { const reason = action === "reject" || action === "block" ? window.prompt("Reason") || "Admin decision" : undefined; const res = await fetch("/api/admin/wallet/cards", { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ id, action, reason }) }); const json = await res.json(); if (json.ok) { toast.success("Wallet status updated"); load(); } else toast.error(json.error || "Failed"); }
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-black text-amber-300">Bound Wallet Review</h1><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl bg-white/10 px-3 py-2 text-xs text-white"><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="VERIFIED">Verified</option><option value="REJECTED">Rejected</option><option value="BLOCKED">Blocked</option></select></div>{loading ? <div className="py-12 text-center text-white/40">Loading...</div> : <div className="space-y-3">{cards.map((card) => <div key={card.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-black text-white">{card.user.username}</span><span className="text-xs text-white/40">bal {formatCoins(card.user.balance)} TK</span><span className="rounded-full bg-amber-500/15 px-2 py-1 text-[10px] font-bold text-amber-200">{card.status}</span></div><div className="mt-2 text-sm font-bold text-emerald-200">{card.label} · {card.accountNo}</div><div className="text-xs text-white/45">{card.accountName || "No account name"} · {new Date(card.createdAt).toLocaleString()}</div>{card.rejectionReason && <div className="mt-2 text-xs text-rose-300">{card.rejectionReason}</div>}</div><div className="flex flex-wrap gap-2">{card.status !== "VERIFIED" && <button onClick={() => act(card.id, "verify")} className="flex items-center gap-1 rounded-lg bg-emerald-500/20 px-3 py-2 text-xs font-bold text-emerald-200"><Check className="h-3 w-3" />Verify</button>}{card.status !== "BLOCKED" && <button onClick={() => act(card.id, "block")} className="flex items-center gap-1 rounded-lg bg-rose-500/20 px-3 py-2 text-xs font-bold text-rose-200"><ShieldOff className="h-3 w-3" />Block</button>}{card.status === "BLOCKED" && <button onClick={() => act(card.id, "activate")} className="flex items-center gap-1 rounded-lg bg-amber-500/20 px-3 py-2 text-xs font-bold text-amber-200"><RotateCcw className="h-3 w-3" />Activate</button>}{card.status !== "REJECTED" && <button onClick={() => act(card.id, "reject")} className="flex items-center gap-1 rounded-lg bg-white/10 px-3 py-2 text-xs font-bold text-white"><X className="h-3 w-3" />Reject</button>}</div></div></div>)}{!cards.length && <div className="py-12 text-center text-white/40">No bound wallets found</div>}</div>}</div>;
}
